version: '3'
services:
    
    back:
        build: 
            context: ./backStomp
            dockerfile: Dockerfile
        image: olejiksin/backstomp
        working_dir: /backStomp
        volumes:
         - ./backStomp:/backStomp
        ports: 
            - 8070:8070
        depends_on:
            - zuul
            - EurekaService
        command: mvn clean spring-boot:run
        
    
    front:
        build: 
            context: ./frontStomp
            dockerfile: Dockerfile
        image: olejiksin/frontstomp
        volumes:
          - ./frontStomp:/usr/src/app
        ports:
            - 3000:3000
        command: npm start
        depends_on: 
            - back
            - zuul
            - EurekaService
    
    EurekaService:
        build: 
            context: ./ServiceRegistry
            dockerfile: Dockerfile
        image: olejiksin/service
        restart: on-failure
        volumes:
          - ./ServiceRegistry:/ServiceRegistry
        ports:
            - 8761:8761
        command: mvn clean spring-boot:run
            
    zuul:
        build: 
            context: ./ZuulService
            dockerfile: Dockerfile
        image: olejiksin/zuul
        restart: on-failure
        volumes:
          - ./ZuulService:/ZuulService
        ports:
            - 8080:8080
        command: mvn clean spring-boot:run
        depends_on: 
            - EurekaService

    