version: '3'
services:
        
    postgres:
        image: postgres
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        volumes:
          - ./data:/var/lib/postgresql/data 
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          PGDATA: 
             ./data
        ports:
          - 5432
    
       
    back:
       build: 
            context: ./back
            dockerfile: Dockerfile
       image: olejiksin/backend
       working_dir: /back
       volumes:
         - ./back:/back
       ports: 
            - 8080:8080
       depends_on:
            - postgres
       network_mode: host
       command: mvn clean spring-boot:run
       
       
   
    front:
        build: 
            context: ./front
            dockerfile: Dockerfile
        image: frontend
        volumes:
          - ./front:/usr/src/app
        ports:
            - 3000:3000
        command: npm start
        depends_on: 
            - back
    