hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 120000
ribbon:
    ConnectTimeout: 30000
    ReadTimeout: 50000

zuul:
  prefix: /api
  routes:
    user:
      path: /cat/**
      serviceId: cat
    country:
      path: /country/**
      serviceId: country
    about:
      path: /about/**
      serviceId: about
    stomp:
      path: /stomp/**
      serviceId: stomp
  ignored-services: "*"
